### ISSUE TITLE
prevent winning by inspect element

### ISSUE THREAD

**Issue by dev-lovedeep** [ContriHUB/memory-game#2]
currently, players can use inspect element and easily win the game by looking at the HTML. Implement some mechanism to prevent this

**Comment by DNA5769** [comment]
is it fine if the player can win if he/she looks at the JS file?

**Comment by dev-lovedeep** [comment]
try to  add some randomness so that the user cannot determine by looking at the code

**Comment by DNA5769** [comment]
sir actually I thought by adding this randomness by shuffling the cards every new game, but that is a separate issue #3
