### ISSUE TITLE
add music when cards match or don't match

### ISSUE THREAD

**Issue by dev-lovedeep** [ContriHUB/memory-game#4]

**Comment by en1gm479** [comment]
I want to work on this issue if you can assign this to me? @dev-lovedeep

**Comment by dev-lovedeep** [comment]
request it from the contrihub website [https://contri-hub.herokuapp.com/](url)

**Comment by en1gm479** [comment]
I tried but it is giving me this error.
`Assignment Request for Issue #4 of memory-game cannot be made by you currently.`

**Comment by dev-lovedeep** [comment]
this issue is having 'restricted' tag , it means it can only be assigned to a 2nd year student. check back later , if this issue stays unsolved for some time, I might make it an 'open to all' issue

> I tried but it is giving me this error. `Assignment Request for Issue #4 of memory-game cannot be made by you currently.`

**Comment by en1gm479** [comment]
Okay sir!

**Comment by AdBharat14** [comment]
the issue still can't be assigned. It doesn't have any restricted tag.

**Comment by dev-lovedeep** [comment]
> the issue still can't be assigned. It doesn't have any restricted tag.
try again , if not assigned to someone I will assign it to you

**Comment by AdBharat14** [comment]
Just tried it... Still showing the same issue of not being assignable.

**Comment by dev-lovedeep** [comment]
> Just tried it... Still showing the same issue of not being assignable.

this issue was assigned to someone else, but the deadline is today evening. If he didn't submit the PR in time, you will be able to request it

**Comment by JainendraDwivedi** [comment]
> extra points for creative sound/music chosen

Sir, may I get these extra points?

**Comment by dev-lovedeep** [comment]
> Sir, may I get these extra points?

gave a +2 check now
