### ISSUE TITLE
add level to the game

### ISSUE THREAD

**Issue by dev-lovedeep** [ContriHUB/memory-game#6]
currently, the game only has a 4 X 3 board, add a 4X5 and 4X7 as medium and hard levels respectively

**Comment by backlit69** [comment]
will the levels progressively increase ? or the player would have tabs on the nav bar to navigate to the level of their choice?

**Comment by dev-lovedeep** [comment]
the user will be able to select the level before starting the game

> will the levels progressively increase ? or the player would have tabs on the nav bar to navigate to the level of their choice?

**Comment by backlit69** [comment]
the issue shows open on the site but there's  this message being displayed "Assignment Request for [Issue #6] of [memory-game] cannot be made by you currently."

**Comment by dev-lovedeep** [comment]
there could be many reasons:
1. restricted issue: only for second years
2. you are already having 2 issue 
3. or already assigned to someone else

currently, this is assigned to someone else

> the issue shows open on the site but there's this message being displayed "Assignment Request for [Issue #6] of [memory-game] cannot be made by you currently."

**Comment by backlit69** [comment]
how will we find if an issue is open/assigned because here on github this issue is open and in asignees it says 'no one assigned' and on page it is open aswell . when will the current assginees period be over .

**Comment by dev-lovedeep** [comment]
from now onwards , we will put the assigned person name in the commet

> how will we find if an issue is open/assigned because here on github this issue is open and in asignees it says 'no one assigned' and on page it is open aswell . when will the current assginees period be over .

**Comment by dev-lovedeep** [comment]
assigned to @harshN-17
