### ISSUE TITLE
initiallly show cards and then hide

### ISSUE THREAD

**Issue by dev-lovedeep** [ContriHUB/memory-game#8]
when the game starts, show the cards for a few seconds so the player can memorize them, and then hide the cards.

**Comment by Prakhar1106** [comment]
Please assign it to me, I am interested

**Comment by dev-lovedeep** [comment]
> Please assign it to me, I am interested

request issue from the website [https://contri-hub.herokuapp.com/](url)

**Comment by Prakhar1106** [comment]
> > Please assign it to me, I am interested
> 
> request issue from the website [https://contri-hub.herokuapp.com/](url)

Error: Assignment Request for [Issue #8](https://github.com/ContriHUB/memory-game/issues/8) of [memory-game](https://github.com/ContriHUB/memory-game) cannot be made by you currently.

**Comment by dev-lovedeep** [comment]
assigned to @Prakhar1106

**Comment by dev-lovedeep** [comment]
closed by pull #26
